FORM_URL_BASE = 'https://docs.google.com/forms/d/e/1FAIpQLSfYBvxATd6XPkAd8Dz313JKgrDyTqGp11TpzB-DKkowp3KZMQ/viewform'

ENTRY_IDS = {
    'District': 'entry.579618161',
    'Type of Settlement': 'entry.62581315',
    'Age': 'entry.2108177138',
    'Gender': 'entry.392252637',
    'Annual Family income': 'entry.1046548052',
    'How many members are there in your family?': 'entry.1808753098',
    'How many earning members are there in your household?': 'entry.793828460',
    'Marital status': 'entry.820595461',
    'Highest level of education completed': 'entry.1395755089',
    'Current occupation/employment status': 'entry.1742625339',
    '1. Which social media platform do you use most frequently?': 'entry.710356990',
    '2. On a typical day during the past 7 days, approximately how much total time did you spend using your mobile phone?': 'entry.1589858844',
    '3. On a typical day during the past 7 days, approximately how much time did you spend on social media?': 'entry.126174581',
    '4. During a typical day, how frequently do you use the following communication methods? [Voice calls]': 'entry.834651560',
    '4. During a typical day, how frequently do you use the following communication methods? [SMS/Text messages]': 'entry.2029203054',
    '4. During a typical day, how frequently do you use the following communication methods? [WhatsApp]': 'entry.706420053',
    '4. During a typical day, how frequently do you use the following communication methods? [Social-media direct messages (DMs)]': 'entry.1705105950',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to stay connected with friends/family]': 'entry.2116116221',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to entertain myself/pass time]': 'entry.468766824',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to follow news/current affairs]': 'entry.1177698879',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to learn new things ]': 'entry.691337894',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to discover products, brands or services]': 'entry.171860570',
    '5. How well do the following describe your reasons for using social media?\n(1 = Not at all true for me, 6 = Completely true for me) [I use social media to follow influencers/content creators]': 'entry.2111816596',
    '6. When the same topic is available in short and long formats, which do you generally prefer?': 'entry.1773544934',
    '7. Please indicate your agreement with the following statements.\n1 = Strongly Disagree, 6 = Strongly Agree [Social media has become part of my everyday routine.]': 'entry.456752513',
    '7. Please indicate your agreement with the following statements.\n1 = Strongly Disagree, 6 = Strongly Agree [I frequently feel the urge to check social media during the day.]': 'entry.1396161532',
    '7. Please indicate your agreement with the following statements.\n1 = Strongly Disagree, 6 = Strongly Agree [I often spend more time on social media than I originally intended.]': 'entry.1000174403',
    '7. Please indicate your agreement with the following statements.\n1 = Strongly Disagree, 6 = Strongly Agree [My social-media use sometimes interferes with my study, work or other responsibilities.]': 'entry.345755319',
    '8. How frequently have you replaced your primary mobile phone/handset?': 'entry.1553859377',
    '9. Do you regularly follow social-media influencers/content creators?': 'entry.1899783310',
    '10. What type of influencers do you mainly follow? \n    (Select up to three)': 'entry.1578949968',
    '11. Thinking about the influencers you follow most closely, please indicate your agreement.\n(1 = Strongly Disagree, 6 = Strongly Agree) [The influencers I follow are knowledgeable about the subjects they discuss.]': 'entry.1868976936',
    '11. Thinking about the influencers you follow most closely, please indicate your agreement.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I generally consider the influencers I follow trustworthy.]': 'entry.1577343751',
    '11. Thinking about the influencers you follow most closely, please indicate your agreement.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I believe the influencers I follow usually give genuine opinions.]': 'entry.1783981040',
    '12. How much do influencers affect your consumption behaviour?\n(1 = Strongly Disagree, 6 = Strongly Agree) [I look at influencer opinions before making some purchase decisions.]': 'entry.1922932420',
    '12. How much do influencers affect your consumption behaviour?\n(1 = Strongly Disagree, 6 = Strongly Agree) [I have tried a product, service or place because an influencer recommended it.]': 'entry.900513057',
    '12. How much do influencers affect your consumption behaviour?\n(1 = Strongly Disagree, 6 = Strongly Agree) [Influencer recommendations can change my opinion about a product or brand.]': 'entry.601599492',
    '12. How much do influencers affect your consumption behaviour?\n(1 = Strongly Disagree, 6 = Strongly Agree) [Influencers sometimes influence how I dress, eat, travel or spend money.]': 'entry.1561667846',
    '13. During the past six months, approximately how often have you purchased clothing, footwear or fashion accessories?': 'entry.1435784565',
    '14. During the past six months, approximately what proportion of your non-food purchases were made online?': 'entry.284969846',
    '15. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I usually feel more confident buying a well-known brand.]': 'entry.1131876691',
    '15. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I am sometimes willing to pay more for a brand that I trust.]': 'entry.433945701',
    '15. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I pay careful attention to whether a product offers good value for money.]': 'entry.1591764256',
    '15. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I would choose a non-branded product if its quality were similar and its price lower.]': 'entry.111378829',
    '16. During a typical week, how often do you consume the following? [Fast food]': 'entry.1378717860',
    '16. During a typical week, how often do you consume the following? [Packaged snacks]': 'entry.1334848747',
    '16. During a typical week, how often do you consume the following? [Food ordered online]': 'entry.1904189220',
    '16. During a typical week, how often do you consume the following? [Home-cooked/traditional food]': 'entry.261950342',
    '17. How often do you eat outside the home?': 'entry.1756802628',
    '18. What are the three most important factors influencing your food choices? (Select three)': 'entry.383379322',
    '19. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [What my friends are buying can influence what I consider buying.]': 'entry.1562974025',
    '19. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I pay attention to products or brands that are popular among people my age.]': 'entry.2145457047',
    '19. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I sometimes choose products that I believe will create a favourable impression on others.]': 'entry.1613791971',
    '19. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I ask other people for advice when I am uncertain about a purchase.]': 'entry.1362348456',
    '20. During the current academic year, have you used paid coaching/private tuition?': 'entry.951397910',
    '21. During the current academic year, have you used digital learning platforms such as YouTube educational channels, Physics Wallah, Unacademy, Coursera, Udemy, SWAYAM, etc.?': 'entry.1856502844',
    '22. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Digital-learning platforms make it easier for me to learn at a time that suits me.]': 'entry.1370098588',
    '22. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I use online educational resources to supplement what I learn through formal education.]': 'entry.1616974520',
    '22. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I am willing to invest in additional learning resources when I believe they will improve my skills or knowledge.]': 'entry.1515849871',
    '23. Which ONE of the following best describes your preferred career direction at present?': 'entry.232379446',
    '24. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I want to achieve a high level of accomplishment in my chosen career.]': 'entry.597372262',
    '24. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I would like to reach a position involving substantial responsibility or leadership.]': 'entry.1026182507',
    '24. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I am willing to obtain additional education or training if it helps me progress in my career.]': 'entry.387315477',
    '25. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Starting my own business is an attractive career possibility for me.]': 'entry.247223212',
    '25. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I am seriously interested in starting a business or venture at some stage.]': 'entry.1568542854',
    '25. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I believe I could develop the skills needed to start and manage a business.]': 'entry.490319624',
    '26. If another place offered a substantially better quality of life, how willing would you be to move?\n(1 =  Completely Unwilling , 6 = Completely Willing) [Another district in Haryana]': 'entry.892659739',
    '26. If another place offered a substantially better quality of life, how willing would you be to move?\n(1 =  Completely Unwilling , 6 = Completely Willing) [Delhi-NCR]': 'entry.957771618',
    '26. If another place offered a substantially better quality of life, how willing would you be to move?\n(1 =  Completely Unwilling , 6 = Completely Willing) [Another state in India]': 'entry.161910597',
    '26. If another place offered a substantially better quality of life, how willing would you be to move?\n(1 =  Completely Unwilling , 6 = Completely Willing) [Another country]': 'entry.989256738',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Financial independence/high income]': 'entry.1541164696',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Owning a good house and valuable possessions]': 'entry.1410926687',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Having a respected/influential occupation]': 'entry.1132424205',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Doing meaningful work]': 'entry.202610217',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Having freedom to make important life decisions]': 'entry.1360450117',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Supporting my parents/family]': 'entry.1593038230',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Having sufficient time outside work]': 'entry.324686827',
    '27. How important are the following in defining success in life for you?\n(1 = Not at all Important  , 6 = Extremely Important) [Being satisfied with my life]': 'entry.447150790',
    '28. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I would consider leaving my current area if it offered a substantially better future.]': 'entry.2094772801',
    '28. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Living in a larger city is attractive to me.]': 'entry.1611665145',
    '28. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I would be willing to live away from my family if it helped me achieve the life I want.]': 'entry.1083935353',
    '29. Please indicate how strongly each source influences your education, career or lifestyle aspirations.\n(1 = Not at all, 6 = Very strongly) [Parents/family]': 'entry.1524216235',
    '29. Please indicate how strongly each source influences your education, career or lifestyle aspirations.\n(1 = Not at all, 6 = Very strongly) [Friends/peers]': 'entry.404113833',
    '29. Please indicate how strongly each source influences your education, career or lifestyle aspirations.\n(1 = Not at all, 6 = Very strongly) [Social-media influencers/content creators]': 'entry.913742804',
    '29. Please indicate how strongly each source influences your education, career or lifestyle aspirations.\n(1 = Not at all, 6 = Very strongly) [People I personally know who are successful]': 'entry.1074342002',
    '29. Please indicate how strongly each source influences your education, career or lifestyle aspirations.\n(1 = Not at all, 6 = Very strongly) [Media/online content]': 'entry.1500990608',
    '30. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I understand that the products people buy can have environmental consequences.]': 'entry.1157045336',
    '30. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I am aware that the way products are produced can affect workers and communities.]': 'entry.1830003997',
    '30. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I consider environmental impact when choosing between otherwise similar products.]': 'entry.1410096301',
    '30. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I prefer products that use less unnecessary packaging.]': 'entry.1498618586',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Use of digital/social media]": 'entry.524202648',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Online shopping]": 'entry.862858495',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Spending on experiences/eating out]": 'entry.660073754',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Concern with brands/fashion]": 'entry.1753100988',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Exposure to different lifestyles]": 'entry.371079005',
    "31. Compared with your parents' generation, how would you describe your own generation's consumption and lifestyle?\n(1 = Much Less, 6 = Much More) [Desire for personal independence]": 'entry.905110560',
}

DATE_QUESTIONS = []
CHECKBOX_QUESTIONS = ['1. Which social media platform do you use most frequently?', '10. What type of influencers do you mainly follow? \n    (Select up to three)', '18. What are the three most important factors influencing your food choices? (Select three)']
