FORM_URL_BASE = '-'

ENTRY_IDS = {
    'District': 'entry.1706238540',
    'Type of Settlement': 'entry.917601778',
    'Age': 'entry.918687913',
    'Gender': 'entry.1877925057',
    'Annual Family income': 'entry.242949735',
    'How many members are there in your family?': 'entry.1018410124',
    'How many earning members are there in your household?': 'entry.152248107',
    'Marital status': 'entry.1641195017',
    'Highest level of education completed': 'entry.54615142',
    'Current occupation/employment status': 'entry.337759755',
    '1. What is your current work status?': 'entry.1000453373',
    '2. What is the nature of your main work?': 'entry.619334320',
    '3. How are you compensated for your main work?': 'entry.1436701990',
    '4. Approximately how many hours do you normally work per week, including paid work, agricultural/family work and unpaid household/care work?': 'entry.1759008938',
    '5. Do you have a bank account in your own name?': 'entry.1866633811',
    '6. Who usually makes decisions about the following matters?\n1 = Woman alone | 2 = Woman and husband/partner jointly | 3 = Husband/partner alone | 4 = Other family member | 5 = Someone else [Your own healthcare]': 'entry.1656319687',
    '6. Who usually makes decisions about the following matters?\n1 = Woman alone | 2 = Woman and husband/partner jointly | 3 = Husband/partner alone | 4 = Other family member | 5 = Someone else [Major household purchases]': 'entry.1917709549',
    '6. Who usually makes decisions about the following matters?\n1 = Woman alone | 2 = Woman and husband/partner jointly | 3 = Husband/partner alone | 4 = Other family member | 5 = Someone else [Use of your own earnings]': 'entry.721130092',
    '6. Who usually makes decisions about the following matters?\n1 = Woman alone | 2 = Woman and husband/partner jointly | 3 = Husband/partner alone | 4 = Other family member | 5 = Someone else [Visits to family or relatives]': 'entry.520337661',
    '7. If you are currently working, approximately how much do you earn from your main work in a typical month?': 'entry.1838177398',
    '8. If another adult woman in your household is currently working, approximately how much does she earn from her main work in a typical month?': 'entry.1019636069',
    '9. If another adult man in your household is currently working, approximately how much does he earn from his main work in a typical month?': 'entry.224161329',
    '10. Among men and women performing broadly similar work in your household/community, how would you describe their earnings?': 'entry.801360099',
    '11. What are the main reasons you think women may earn less than men for similar work?\nSelect up to three.': 'entry.1979347916',
    "12. Before today, had you heard of the women's helpline 181?": 'entry.964063526',
    '13. Which of the following support mechanisms for women are you aware of?\nSelect all that apply.': 'entry.1121487286',
    '14. If a woman in your community experienced domestic violence, harassment or another form of gender-based violence, how confident are you that she would know where to seek help?': 'entry.10163977',
    '15. Please indicate your agreement with the following statements.\n1 = Strongly Disagree | 2 = Disagree | 3 = Slightly Disagree | 4 = Slightly Agree | 5 = Agree | 6 = Strongly Agree [Women in my community can seek help without facing major social stigma.]': 'entry.50803750',
    "15. Please indicate your agreement with the following statements.\n1 = Strongly Disagree | 2 = Disagree | 3 = Slightly Disagree | 4 = Slightly Agree | 5 = Agree | 6 = Strongly Agree [Women's support services are accessible when they are needed.]": 'entry.1481807223',
    '15. Please indicate your agreement with the following statements.\n1 = Strongly Disagree | 2 = Disagree | 3 = Slightly Disagree | 4 = Slightly Agree | 5 = Agree | 6 = Strongly Agree [Authorities generally respond appropriately when women report violence or harassment.]': 'entry.1913326566',
    '15. Please indicate your agreement with the following statements.\n1 = Strongly Disagree | 2 = Disagree | 3 = Slightly Disagree | 4 = Slightly Agree | 5 = Agree | 6 = Strongly Agree [Women can report violence or harassment without fear of retaliation.]': 'entry.211009206',
    "16. Have you or any woman in your household ever used a women's helpline or support service for a problem involving harassment, violence or another gender-related concern?": 'entry.1371740840',
    'If yes: How would you describe the experience?': 'entry.745926765',
    '17. How old is the child?': 'entry.2076531961',
    '18. Is the child currently enrolled in school?': 'entry.1001871957',
    '19. During the current school year, how regularly has the child attended school?': 'entry.2087982699',
    '20. Has the child ever dropped out of school?': 'entry.2019174964',
    'If yes, what was the main reason?': 'entry.1569473229',
    '21. During the last 7 days, did the child engage in any paid or unpaid work outside the household?': 'entry.241491208',
    '22. During the last 7 days, did the child perform household tasks such as cooking, cleaning, fetching water, shopping or caring for children, elderly or sick family members?': 'entry.1168944438',
    'If yes:\nApproximate time spent on household tasks during the last 7 days:': 'entry.727035385',
    '23. Does the child currently have adequate access to the following? [Healthcare when needed]': 'entry.802838941',
    '23. Does the child currently have adequate access to the following? [Recommended immunisations]': 'entry.1581575802',
    '23. Does the child currently have adequate access to the following? [Safe drinking water]': 'entry.1283121350',
    '23. Does the child currently have adequate access to the following? [Functional sanitation facilities at school\t]': 'entry.1974445553',
    '23. Does the child currently have adequate access to the following? [School meal/PM POSHAN\t]': 'entry.1152387584',
    '23. Does the child currently have adequate access to the following? [Digital access needed for education]': 'entry.1208139644',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Grains, roots and tubers]': 'entry.224576232',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Pulses, beans and peas]': 'entry.1267726910',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Nuts and seeds]': 'entry.1304852772',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Milk and dairy products]': 'entry.743259963',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Meat, poultry or fish]': 'entry.727473729',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Eggs]': 'entry.1116745509',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Dark green leafy vegetables]': 'entry.1859843500',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Other vegetables]': 'entry.385209845',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Vitamin-A-rich fruits/vegetables]': 'entry.722352704',
    '24. During the previous 24 hours, did you consume food from the following food groups? [Other fruits]': 'entry.698549740',
    '25. On a typical day, how many meals do you eat?': 'entry.357352947',
    '26. How often do you consume packaged, processed or fast food?': 'entry.2040298642',
    '27. During the past 12 months, have you received or used any of the following nutrition-related services?\nSelect all that apply.': 'entry.1537018201',
    '28. How would you rate the quality of nutrition services available through Anganwadi/other public nutrition services in your area?': 'entry.1261189049',
    '29. During the past 12 months, which of the following health problems have you experienced?\nSelect all that apply.': 'entry.1222241832',
    '30. When you or a household member needed healthcare during the past 12 months, where did you usually seek treatment first?': 'entry.1424847721',
    '31. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Healthcare facilities that I need are available within a reasonable distance from my household.]': 'entry.1736624167',
    '31. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [The cost of consultation, medicines and treatment is affordable for my household.]': 'entry.1914762071',
    '31. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [I can obtain healthcare when I need it without major problems such as long waiting times or lack of doctors/medicines.]': 'entry.1814270213',
    '31. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Transportation does not prevent me from obtaining healthcare when needed.]': 'entry.984165537',
    '31. Please indicate your agreement with the following statements.\n(1 = Strongly Disagree, 6 = Strongly Agree) [Healthcare providers generally treat patients with adequate care and respect.]': 'entry.2132168884',
    '32. Does your household currently have any form of health insurance or government health coverage?': 'entry.1492188858',
    '33. Which of the following difficulties have you experienced when seeking healthcare?\nSelect all that apply.': 'entry.371997992',
    '34. Have you used any digital health service during the past 12 months?\nExamples: online doctor consultation, online appointment booking, digital health records, telemedicine, online health information, e-pharmacy, etc.': 'entry.1760658341',
    '35. Overall, how would you rate the healthcare services available to your household?': 'entry.1280289935',
    '36. Before today, had you heard of the Beti Bachao Beti Padhao Scheme?': 'entry.2145390203',
    '37. How familiar are you with the main objectives of the Beti Bachao Beti Padhao (BBBP) Scheme?': 'entry.931706594',
    '38. In your opinion, how effective has the Beti Bachao, Beti Padhao (BBBP) Scheme been in improving opportunities for girls and women?': 'entry.468695569',
    "39. Compared with the past, has the importance given to girls' education in your community increased?": 'entry.1077590732',
    '40. In your opinion, how effective have government initiatives such as Beti Bachao, Beti Padhao been in reducing school dropout among girls in your community?': 'entry.1235334838',
    '41. Are you aware of any government financial or welfare programs that support the education or future of girl children, such as Sukanya Samriddhi Yojana?': 'entry.1189132750',
}

DATE_QUESTIONS = []
CHECKBOX_QUESTIONS = ['11. What are the main reasons you think women may earn less than men for similar work?\nSelect up to three.', '13. Which of the following support mechanisms for women are you aware of?\nSelect all that apply.', '27. During the past 12 months, have you received or used any of the following nutrition-related services?\nSelect all that apply.', '29. During the past 12 months, which of the following health problems have you experienced?\nSelect all that apply.', '33. Which of the following difficulties have you experienced when seeking healthcare?\nSelect all that apply.']
